### ISSUE TITLE
Keynotes

### ISSUE THREAD

**Issue by ghost** [danewatkins/sar#15]
Martin Crowley is a Reader in Modern French Thought and Culture, at the University of Cambridge. He is  an author of books on Marguerite Duras, Robert Antelme, contemporary French fiction and film, and the politics of finitude and is currently writing a book on political agency in Bruno Latour, Bernard Stiegler, and Catherine Malabou.

ABSTRACT

**_Exploding. Plastic. Inevitable?_**

Eating itself, artistic research goes POP! 
Pop: so plastic. 
Which moulds, bends, and itself explodes.

The work of philosopher Catherine Malabou takes as its central organizing concept a particular notion of plasticity, defined by three tendencies: to give form, to receive form, and to explode. Unpacking Malabou’s concept, this talk will examine in particular its role in sustaining a notion of immanent discontinuity: namely, drastic, interruptive change that takes place within a system, process, or individual. The talk will go on to consider the interest and uses of this notion, with reference to conceptions of political agency and artistic practice.

_________________
Elaine Gan is an artist and scholar who studies how human-plant interactions shape geopolitical histories. She is a Mellon Fellow in Digital Humanities, affiliated with the departments of Anthropology and Media Arts + Practice at University of Southern California. She has also been the art director of Aarhus University Research on the Anthropocene (AURA) in Denmark since 2013, and a fellow of the Whitney Museum - Independent Study Program and the New York Foundation for the Arts (NYFA). Her most recent collaborative projects include editing an anthology titled Arts of Living on a Damaged Planet: Ghosts and Monsters of the Anthropocene (Univ of Minnesota Press 2017); convening a seminar on Feral Technologies in the Technosphere for Haus Kulturen der Welt (HKW) in Berlin (2016); and curating an artscience exhibition titled DUMP! Multispecies Making and Unmaking (Kunsthal Aarhus 2015). She is now working on a book and digital project titled Time Machines: Coordinating Rice Ecologies and Empires.

ABSTRACT

Art as Method For Working the Ontological Limits of Plants, People, and Fungi (While Never Fully Digesting What Is Going On In The Anthropocene)

The Anthropocene seems to throw everything we know about the world into a tailspin. Faced with multiple crises that are unfolding unevenly across bodies, places, and times, we have an urge to increase what we know in order to survive. More data, more stories, more pixels, more maps. And yet to acknowledge the Anthropocene as a geological epoch marked by human domination and planetary ruin is to radically question the keystones of artistic life: individual freedom, production, and creative innovation. This paper calls for changing how we know, not adding to what we know. I consider art as a collaborative method of attunement with more-than-human assemblages whose endurances depend on interplays of time and historical contingency. I present ongoing studies of the temporalities of plants, people, and fungi, and the unruly research that might render them concrete as well as poetic. Human and nonhuman, individual and collective, fiction and science are recomposed, cannibalizing what we know in order to experiment with how we might sense and live otherwise. #

________________

Ayesha Hameed’s work explores contemporary borders and migration, critical race theory, Walter Benjamin, and visual cultures of the Black Atlantic.  Her work has been performed or exhibited at ICA London (2015), Haus der Kulturen der Welt, Berlin (2014), at The Chimurenga Library at the Showroom, London (2015), Oxford Programme for the Future of Cities, Oxford (2015), Edinburgh College of Art (2015), Kunstraum Niederoesterreich Vienna (2015), Pavillion, Leeds in 2015, Homeworks Space Program, Beirut (2016), the Bartlett School of Architecture (2016), Mosaic Rooms (2017) RAW Material Company, Dakar (2017).

Her publications include contributions to Forensis: The Architecture of Public Truth (Sternberg Press 2014), We Travelled The Spaceways (Duke University Press forthcoming 2018), Unsound/Undead (Univocal, Forthcoming 2018); and books including Futures and Fictions (co-edited with Simon O’Sullivan and Henriette Gunkel Repeater 2017)  and Visual Cultures as Time Travel (with Henriette Gunkel Sternberg, forthcoming 2018). She is currently a Lecturer in Visual Cultures and formerly a Research Fellow with Forensic Architecture at the Centre for Research Architecture at Goldsmiths University, London.

ABSTRACT

Black Atlantis: Retrograde Futurism

This lecture performance is composed of notes on a film to be made and an essay to be written.  On April 29, 2006, a twenty-foot boat was spotted off the south-eastern coast of Barbados. On board, eleven bodies were found by the coastguards, preserved and desiccated by the sun and salt water. The ghost ship was adrift for four months on the Atlantic Ocean. It set sail on Christmas day in Praia in the Cape Verde Islands, full of migrants from Senegal, Guinea Bissau, and Gambia, en route to the Canary Islands. Each of these men paid £890 for their place on the boat. Four months later the boat was found on the coast of Barbados. 

This is an inadequate telling of this story that draws on the materials and tools at hand to make sense of the complicity of weather, ocean currents and state violence in the journey of this ship. Hovering between the film and the essay form is a questioning of the adequacy of the measuring of histories and affects connected to crossing, languages to make evident the materiality of the sea, and the both measurable and immeasurable horror contained in the figure of the ghost ship.

______________
Alexandra Murray-Leslie
Dr. Alexandra Murray-Leslie is co-founder of the trans-disciplinary art band Chicks on Speed, a collective of culture workers who apply subversive DIY ethics to interrogate the boundaries of academia, pop music, craft, performance art, new musical instrument design, textiles and theatrical fashion. She is currently guest academic artist at Animal Logic Academy, Faculty of Transdisciplinary Innovation, The University of Technology Sydney and Research Associate at (CRCDM) Centre for Research Creation in Digital Media, Sunway University, Kuala Lumpur. Her practice-based research focuses on the design and development of computer enhanced foot devices for theatrical audiovisual expression.

ABSTRACT
information forthcoming
_______________
Florian Schneider
information forthcoming

**Comment by danewatkins** [comment]
would you like this in now or wait until we have all four?

**Comment by ghost** [comment]
Let’s wait till we have another one

Anya Lewin, PhD
Associate Professor (Reader) in Art and Moving Image
Programme Leader MA Contemporary Art Practice
Academic Liaison Tutor MFA and Co-Coordinator PHD Transart

________________________________
