### ISSUE TITLE
email bars

### ISSUE THREAD

**Issue by ghost** [danewatkins/sar#4]
As the email bars set up the email and the subject header text should we just cut this text:
For further enquiries about the workshop please contact: andrew.prior@plymouth.ac.uk (please use the subject header “ARWEI Workshop”)
and be e- mailed to artsresearch@plymouth.ac.uk (please use the subject header “ARWEI Workshop Application”)

I leave that to your judgement

**Comment by danewatkins** [comment]
I left both in so that viewers could read the email address and see that it was a plymouth.ac.uk account, I put the bars in for greater visibility, I have replicated information throughout the page in the hope that people can find it wherever or however they look for it, but also happy to change.

**Comment by ghost** [comment]
yes that makes sense
